[git]
conventional_commits = false
commit_parsers = [
    { message = '^\s*v\d+\.\d+\.\d+\s*$', skip = true },
    { message = '^/ ', skip = true },
    { message = '^\+ ', group = "新增" },
    { message = '^\- ', group = "修复" },
    { message = '^\* ', group = "优化" },
    { message = '^Merge branch', skip = true },
    { message = ".*", group = "其他" },
]

[changelog]
body = """{% for group_name in ["新增", "优化", "修复", "其他"] %}
{% set group_commits = commits | filter(attribute="group", value=group_name) %}
{% if group_commits | length > 0 %}
### {{ group_name }}
{% for commit in group_commits %}
{{ commit.message }}
{% endfor %}
{% endif %}
{% endfor %}"""
trim = true
