name: Sync to Gitee

permissions:
  contents: read

on:
  push:
    branches: [main, 26.1.2, 26.2]
    tags:
      - 'v*'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  mirror-repo:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/${{ github.repository_owner }}
          dst: gitee/Bluesky-kk
          dst_key: ${{ secrets.GITEE_PRIVATE }}
          dst_token: ${{ secrets.GITEE }}
          static_list: "${{ github.event.repository.name }}"
          force_update: true
